### ISSUE TITLE
[V1.3.0b2] Rear Speakers creation without being present

### ISSUE THREAD

**Issue by czesiu20** [MrBearPresident/JBL_Soundbar#15]
The devices for the Left and Right rear speakers should not be created when not present (JBL BAR 300).
version 1.3.0b2

**Comment by MrBearPresident** [comment]
All questions will be handled in:
- #16

**Comment by czesiu20** [comment]
Small regression in release [V.1.3.0]. Rear devices appeared again for my JBL 300

**Comment by MrBearPresident** [comment]
Could you test these files:
- https://github.com/MrBearPresident/JBL_Soundbar/issues/16#issuecomment-2573461107

**Comment by czesiu20** [comment]
Very strange. Both are reported:
`response_json:
  error_code: "0"
  rears:
    - capicity: 0
      channel: left
      charging: false
      docked: false
      status: offline
      volume: 2
    - capicity: 0
      channel: right
      charging: false
      docked: false
      status: offline
      volume: 2
`

**Comment by czesiu20** [comment]
Another regression. Also Smart Mode error appeared again:
```Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.jbl_integration.coordinator
Źródło: custom_components/jbl_integration/coordinator.py:495
integracja: JBL Integration (dokumentacja, Problemy)
Pierwsze zdarzenie: 09:10:15 (136 zdarzenia)
Ostatnio zalogowany: 09:44:14

Error getting SmartMode:```

**Comment by czesiu20** [comment]
And the response from the API:
```
data:
  file: skrypty/GetSmartMode.py
  cache: false
cert_path: custom_components/jbl_integration/Cert.pem
key_path: custom_components/jbl_integration/Key.pem
url: https://10.0.0.119/httpapi.asp?command=getSmartMode
headers:
  Accept-Encoding: gzip

```
